version: '3.7'

services:
  app:
    container_name: app
    command: ["gunicorn", "-c", "/app/gunicorn_config.py", "app"]
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        host: 0.0.0.0
        port: 80
        broker_host: broker
        broker_port: 5672
        broker_user: guest
        broker_pass: guest
        apm_host: http://apm:8200
        gunicorn_log_level: INFO
        gunicorn_workers: 4
        db_uri: postgres://user:password@database/elk
    ports:
      - 8000:80
    links:
      - broker
      - apm
      - database
    depends_on:
      - broker
      - apm
      - database
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health-check"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  database:
    container_name: database
    image: postgres:alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_DB: elk
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - ./initial.sql:/docker-entrypoint-initdb.d/init.sql

  broker:
    build:
      context: .
      dockerfile: docker/rabbitmq.Dockerfile
    container_name: broker
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_NODE_PORT: 5672
    ports:
      - 5672:5672
      - 15672:15672

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.2
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=elasticsearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    healthcheck:
      test: curl --cacert /usr/share/elasticsearch/config/certs/ca/ca.crt -s https://localhost:9200 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 30s
      timeout: 10s
      retries: 5

  apm:
    image: docker.elastic.co/apm/apm-server:7.4.2
    container_name: apm
    ports:
      - 8200:8200
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
      - kibana
    environment:
      - output.elasticsearch.hosts='["http://elasticsearch:9200"]'
      - apm-server.host=0.0.0.0:8200

  heartbeat:
    image: docker.elastic.co/beats/heartbeat:7.4.2
    container_name: heartbeat
    command: --strict.perms=false -e
    depends_on:
      - elasticsearch
      - kibana
    healthcheck:
      test: heartbeat test config
      interval: 30s
      timeout: 15s
      retries: 5


  logstash:
    container_name: logstash
    image: logstash:7.4.2
    environment:
      xpack.monitoring.elasticsearch.hosts: '["http://elasticsearch:9200"]'
    depends_on:
      - elasticsearch
      - kibana
      - broker
      - heartbeat
    links:
      - elasticsearch
      - broker
    healthcheck:
      test: bin/logstash -t
      interval: 60s
      timeout: 50s
      retries: 5
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./pipeline/:/usr/share/logstash/pipeline/


  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.4.2
    environment:
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    healthcheck:
      test: curl --cacert /usr/share/elasticsearch/config/certs/ca/ca.crt -s https://localhost:5601 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  data01:
    driver: local