"""empty message

Revision ID: 9c6832308e56
Revises: 
Create Date: 2019-11-27 20:48:21.405199

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '9c6832308e56'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    user = op.create_table(
        'user',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('username', sa.String(length=80), nullable=False),
        sa.Column('email', sa.String(length=120), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email'),
        sa.UniqueConstraint('username'),
    )
    op.bulk_insert(
        user,
        [
            {'username': 'Bruce Wayne', 'email': 'bruce.wayne@wayneenterprise.com'},
            {'username': 'Clark Kent', 'email': 'clark.kent@planetdiary.com'},
            {'username': 'Diana Prince', 'email': 'diana.prince@defense.gov'},
            {'username': 'Barry Allen', 'email': 'barry.allen@scpd.gov'},
        ],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
